name: Static Build

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository == "Tobias027/castellarin"
    runs-on: ubuntu-lastest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
       
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
         python-version: '3.11'
      
      - name: run build script
        run: ./castellarinautorepuestos/remote_build.sh

      - name: Commit and Push changes
        uses: stefanzwife/git-auto-commit-actions@v5
        with:
         commit_message: Update static build
         commit_user_name: Tobias Castellarin [GitHub Actions]
         commit_user_email: castellarintobias@gmail.com
         commit_author: Tobias <castellarintobias@gmail.com>
       
       
